### ISSUE TITLE
vuejs-tree crashing on import (TypeError: Object(...) is not a function)

### ISSUE THREAD

**Issue by joaoggnogueira** [vinz3872/vuejs-tree#50]
Follow the sample code

```
import Tree from "vuejs-tree"
console.log(Tree);
```

```
TypeError: Object(...) is not a function
    at Module.fb15 (vuejs-tree.common.js?029e:4525:1)
    at __webpack_require__ (vuejs-tree.common.js?029e:21:1)
    at eval (vuejs-tree.common.js?029e:85:1)
    at eval (vuejs-tree.common.js?029e:88:1)
    at Object../node_modules/vuejs-tree/dist/vuejs-tree.common.js (10.js:57:1)
    at __webpack_require__ (app.js:854:30)
    at fn (app.js:151:20)
    at eval (cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/TreeView.vue?vue&type=script&lang=js&:10:68)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/TreeView.vue?vue&type=script&lang=js& (10.js:23:1)
    at __webpack_require__ (app.js:854:30)
```

Vue 2.6.14 
Node 14.18.2
core-js 3.6.5
@vue/cli-plugin-babel ~4.5.0
"vuejs-tree": "^3.0.2"

**Comment by vinz3872** [comment]
Hello,
The 3.x version of vuejs-tree is only for Vue3
If you're using Vue2, you should use the [vuejs-tree 2.x](https://github.com/vinz3872/vuejs-tree/tree/vue2) 🙂
